### ISSUE TITLE
Bugs and Issues

### ISSUE THREAD

**Issue by swonb** [assematt/COMP313#4]
- [x] Exit button in Main Menu is not working (not sure if it is only happening on my computer) @swonb 
- [x] When clicking the Pause button after changing the speed to 2X, the speed decreases instead of pausing the game; the game pauses by clicking Pause twice. @swonb 
- [x] After complete the previous level with the speed of 2X, the UI on the top-right corner changes '1X' at the next level, but the actual game speed remains 2X. @swonb

**Comment by swonb** [comment]
#1 Exit Button issue has fixed and pushed on 'Debugging/SeungWon' branch, but I am not able to build the game as PC executable files in my system, so it has not been tested on the build version yet.

**Comment by swonb** [comment]
2 - Pause button function after changing the game speed has been fixed and uploaded. Now, the pause button pauses the game with a single click regardless of the speed, and clicking the resume button resumes to the same speed as the game UI.

**Comment by swonb** [comment]
5 - Matching speed after changing the speed at the previous level has been fixed.

**Comment by earldenzel** [comment]
Since all tasks here are done, closing this issue
